import Head from "next/head"
import { containerHome } from "../../styles/pages.css"
import { Header } from "../../components/header"
import { PokemonCardSet } from "../../modules/pokemon-card-set"
import { Pokemon } from "../../api/pokedex-client"
import { useAppSelector, useAppDispatch } from "../../store/hooks"
import { searchByName, searchByType } from "../../store/pokemon/homeSlice"

interface IHomeProps {
  initialList: Pokemon[]
  typeList: string[]
}

export default function Home({ initialList, typeList }: IHomeProps) {
  const { results, name, type } = useAppSelector((state) => state.home)
  const dispatch = useAppDispatch()

  const handleSearchBar = (event: React.FormEvent<HTMLInputElement>) => {
    const name = event.currentTarget.value
    dispatch(searchByName(name))
  }

  const handleTypeSelection = (event: React.FormEvent<HTMLSelectElement>) => {
    const element = event.target as HTMLSelectElement
    if (element.value === "---") {
      dispatch(searchByType(undefined))
    } else {
      dispatch(searchByType(element.value))
    }
  }

  return (
    <div className={containerHome}>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        initSearch={{ name, type }}
        onSearch={handleSearchBar}
        onSelect={handleTypeSelection}
        typeList={typeList}
      />

      <PokemonCardSet list={results.length === 0 && !type ? initialList : results} />
    </div>
  )
}
